name: whatado
description: An app to bring the "social" back into "social media".
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injector: ^2.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  quiver: ^3.0.1
  flutter_lorem: ^2.0.0
  expandable_text: ^2.2.0
  pull_to_refresh: ^2.0.0
  artemis: '^7.0.0-beta.3'
  json_annotation: ^4.0.1
  equatable: ^2.0.0
  gql: '>=0.12.3 <1.0.0'
  meta: '>=1.0.0 <2.0.0'
  graphql_flutter: ^5.0.0
  http: ^0.13.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  json_serializable: ^4.1.3
  path_provider: ^2.0.2
  web_socket_channel: ^2.1.0
  firebase_storage: ^10.0.1
  firebase_core: ^1.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/text_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700